# Generated by Django 6.0 on 2026-02-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosmodels',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='image/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='productosmodels',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug'),
        ),
    ]
