# Generated by Django 6.0 on 2026-02-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_productosmodels_img_productosmodels_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosmodels',
            name='img',
            field=models.ImageField(upload_to='image/', verbose_name='Imagen'),
        ),
    ]
