# Generated by Django 6.0 on 2026-02-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_alter_productosmodels_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosmodels',
            name='favorito',
            field=models.PositiveIntegerField(default=0, verbose_name='Favorito'),
        ),
    ]
