# Generated by Django 6.0 on 2026-02-12 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiudadesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Ciudades',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ciudades',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='usuarioordinario',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.ciudadesmodel'),
        ),
    ]
