# Generated by Django 6.0 on 2026-02-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosmodel',
            name='estado',
            field=models.CharField(choices=[('', ''), ('', ''), ('', '')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pedidosmodel',
            name='pedido',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
