# Generated by Django 6.0 on 2026-02-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_pedidosmodel_estado_alter_pedidosmodel_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosmodel',
            name='estado',
            field=models.CharField(choices=[('pendiente', '...'), ('cancelado', 'X'), ('entregado', 'ok')], max_length=50),
        ),
    ]
