# Generated by Django 6.0 on 2026-02-18 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_ciudadesmodel_usuarioordinario_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='PEdidosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.JSONField(blank=True, default=dict, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedidos',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'Pedidos',
            },
        ),
    ]
