# Generated by Django 6.0 on 2026-02-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_pedidosmodel_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosmodel',
            name='pago',
            field=models.FloatField(default=0, verbose_name='PrecioTotal'),
        ),
    ]
