# Generated by Django 6.0 on 2026-02-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_pedidosmodel_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosmodel',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('cancelado', 'Cancelado'), ('entregado', 'Entregado')], max_length=50),
        ),
    ]
